### ISSUE TITLE
Add NodeBB composer default plugin

### ISSUE THREAD

**Issue by lagonnebula** [psychobunny/nodebb-plugin-custom-pages#21]
Hello,

I would like to add the editor on directly on the page and gave access to it for a certain group of user.

An user group : like "pageEditors", who don't have acces to the admin panel but can edit the page.

**Comment by psychobunny** [comment]
(Sorry for the late reply) 
This sounds really difficult and out of scope of this plugin. Though, since this uses the widget system perhaps you can file this under the [widgets repo](https://github.com/NodeBB/nodebb-widget-essentials) for a "Post Widget", which would display a post and allow people to edit it
