### ISSUE TITLE
Can't add more than 20 pages

### ISSUE THREAD

**Issue by orisnas** [psychobunny/nodebb-plugin-custom-pages#45]
NodeBB v1.4.5
Can't add more than 20 pages

**Comment by psychobunny** [comment]
That's weird. Is there any error in the browser console or server side?

**Comment by orisnas** [comment]
No.It says 'success' but there's no new tpl in extend→widget.

**Comment by psychobunny** [comment]
I can't repro this on latest plugin / nodebb. Managed to add 23 pages and they do show up on the widgets page. Maybe try the latest version of the plugin / nodebb? 

![widgets](https://user-images.githubusercontent.com/654670/29685611-ffdb0196-88e3-11e7-8f79-fbe9716d96aa.PNG)

**Comment by psychobunny** [comment]
Hi @orisnas, just letting you know we did end up managing to reproduce your error today. Apologies! The fix is available in latest core as of 
https://github.com/NodeBB/NodeBB/commit/13e56ad5f3e02d40b63bc402c4584738b1aa5c46

(see https://github.com/NodeBB/NodeBB/commit/ea8cf6545c170e8811ba018e6d8e682cc2fc7d8c for actual fix)

Sorry and thanks for reporting!
